### ISSUE TITLE
Licence + Release

### ISSUE THREAD

**Issue by Eluminae** [march-linux/mimi#12]
Hey ! I'd like to package mimi on VoidLinux.

I'll need a tagged release and, optionally, a Licence. 
I saw some other issues about this subject.

Thanks a lot !

**Comment by anjandev** [comment]
@taylorchu 

I would like to use mimi (https://github.com/march-linux/mimi) for my own project:

https://sr.ht/~mil/Sxmo/

Please choose any free software license for your project so we (and others https://github.com/march-linux/mimi/issues/12) can use your project.

Thank you

**Comment by taylorchu** [comment]
done!
